name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key macbook@34.131.106.109 << 'EOF'
            cd /var/www/html
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart apache2
          EOF
