name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key macbook@34.131.106.109 << 'EOF'
            cd ~/demo-gcp
            git pull origin main

            # Install dependencies and build the project
            npm install
            npm run build

            # Copy the build output to /var/www/html
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            # Restart Apache
            sudo systemctl restart apache2
          EOF
